//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERVERInternetMarket
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InternetMarketEDMXContainer : DbContext
    {
        public InternetMarketEDMXContainer()
            : base("name=InternetMarketEDMXContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> CategorySet { get; set; }
        public virtual DbSet<Brend> BrendSet { get; set; }
        public virtual DbSet<NameProdact> NameProdactSet { get; set; }
        public virtual DbSet<Cost> CostSet { get; set; }
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<Admin> AdminSet { get; set; }
        public virtual DbSet<Basket> BasketSet { get; set; }
    }
}
